name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [14.x, 16.x, 17.x]
        docusaurus-version:
          - "v2.0.0-beta.17"
          - "canary"

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'

    - run: yarn install --frozen-lockfile
    - run: yarn lint

    - run: yarn -W add '@docusaurus/core@${{ matrix.docusaurus-version }}' '@docusaurus/preset-classic@${{ matrix.docusaurus-version }}'
    - run: yarn --cwd packages/docusaurus-search-local add --dev '@docusaurus/module-type-aliases@${{ matrix.docusaurus-version }}' '@docusaurus/plugin-content-blog@${{ matrix.docusaurus-version }}' '@docusaurus/plugin-content-docs@${{ matrix.docusaurus-version }}' '@docusaurus/plugin-content-pages@${{ matrix.docusaurus-version }}' '@docusaurus/theme-common@${{ matrix.docusaurus-version }}' '@docusaurus/theme-classic@${{ matrix.docusaurus-version }}' '@docusaurus/types@${{ matrix.docusaurus-version }}'

    - run: yarn --cwd packages/docusaurus-search-local build:server
    - run: yarn --cwd packages/docusaurus-search-local build:client

    # Install OS dependencies
    # Run `apt update` beforehand to avoid 404 Not Found errors during apt install.
    - run: sudo apt update && yarn playwright install-deps
    # Install Browsers
    - run: yarn playwright install

    - run: yarn --cwd packages/example-docs build
    - run: |
        [ "$(grep -cF '/docs/doc2'      packages/example-docs/build/search-index-docs-default-1.0.0.json)"   = "1" ]
    - run: |
        [ "$(grep -cF '/docs/next/doc2' packages/example-docs/build/search-index-docs-default-current.json)" = "1" ]

    - run: yarn test
    - run: yarn --cwd packages/example-docs serve &
    - run: yarn test:e2e --browser=all

    # TODO: Cannot run browser tests for these for now.
    - run: yarn --cwd packages/example-docs build --config docusaurus.config.noTrailingSlash.js
    - run: yarn --cwd packages/example-docs build --config docusaurus.config.subDirectory.js
    - run: yarn --cwd packages/example-docs build --config docusaurus.config.noTrailingSlashSubdirectory.js

    # Test `ignore` option
    - run: yarn --cwd packages/example-docs build --config docusaurus.config.ignore-valid.js > /tmp/out 2>&1
    - run: |
        [ "$(grep -cF '[Local Search] [INFO]: Ignored pages: /docs/doc2, /' /tmp/out)"                                                         = "2" ]
    - run: |
        [ "$(grep -cF '[Local Search] [WARN]: The following pages in the "ignore" config option were not encountered: /nonexisting' /tmp/out)" = "2" ]
    - run: |
        [ "$(grep -cF '/docs/doc2'      packages/example-docs/build/search-index-docs-default-1.0.0.json)"   = "0" ]
    - run: |
        [ "$(grep -cF '/docs/next/doc2' packages/example-docs/build/search-index-docs-default-current.json)" = "0" ]

    - run: '! yarn --cwd packages/example-docs build --config docusaurus.config.ignore-invalid-1.js'
    - run: '! yarn --cwd packages/example-docs build --config docusaurus.config.ignore-invalid-2.js'
